### ISSUE TITLE
Accomplishments Epic: Website

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/admin-accomplishments#4]
### Overview
We need to manage the accomplishment issues for our project or CoP, so that the website team can publish the yearly accomplishments on the hackforla.org for our project.

### Action Items
- [ ] Go to the marketing repo labels page and click on the project label that matches this project (resource 1.04)
   - [ ] Copy the URL and add it to resource 2.01
   - [ ] add all issue links to a comment on this issue under this heading
   ```
   ### [Replace NAME OF PROJECT or CoP] Team Task issues
   - 
   ```
- Check the issue titles you found and indicate which of these they have 
   - [ ] Accomplishment Summary for Website [YYYY]
- Search the project's repo for any accomplishment issues, add any links you find to another comment
  - [ ] Go to the project repo issue tab (resource 2.02)
  - [ ] search for accomplishment issues.  They may have a p-feature: accomplishments label
   ```
   ### Project or CoP's repo issue searches
   ```
     - [ ] put the links relevant to that search under the following heading
       - for each search you perform, indicate what you searched in the filter bar to get the result and link it to the URL (e.g.,)
   ```
   #### [Replace with what you searched for in the Filter bar]
   - 
   ```
- [ ] add a label `ready for product management lead`
- [ ] move to the questions / review column
   - [ ] we will review the issues they are missing (indicated above) and determine if we need to make issues for this project.
- [ ] Once we feel the epic has all the relevant child issue (this might involve making new issue)
   - [ ] Add the epic issue to their project board and cop product management agenda for discussion

#### Links provided by this issue
- 1.01 [List of Project or CoP Name Labels](https://docs.google.com/spreadsheets/d/14pzhhBXBsD-l1zrHoAfS7b7KVZ6_RgIH_0gWW9EaqV4)
- 1.02 [Accomplishments Repo, label page](https://github.com/hackforla/admin-accomplishments/labels)
- 1.03 [Marketing Repo, Issue Tab, label:"project todo"](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+label%3A%22project+todo%22)
- 1.04 [Marketing Labels page, search "P:"](https://github.com/hackforla/marketing/labels?q=P%3A)
- 1.05 This issue is a subset of: Create project and CoP Accomplishment Epics #3

#### Links created by working on this issue
- 2.01 [Replace with PROJECT OR CoP NAME on accomplishments repo, issue tab]
- 2.02 [Replace with PROJECT or CoP NAME repo, Issues tab]

**Comment by ExperimentsInHonesty** [comment]
### HfLA Website Team Task issues
- https://github.com/hackforla/admin-accomplishments/issues/4

**Comment by ExperimentsInHonesty** [comment]
#### [Replace with what you searched for in the Filter bar]
- [label:"p-feature: accomplishments" ](https://github.com/hackforla/website/issues?q=is%3Aopen+is%3Aissue+label%3A%22p-feature%3A+accomplishments%22)
