### ISSUE TITLE
Accomplishments Epic: Civic Tech Index

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/admin-accomplishments#5]
### Overview
We need to manage the accomplishment issues for our project or CoP, so that the website team can publish the yearly accomplishments for our project on the Hack for LA website.

#### Details
Where the accomplishments will be published (see resource 1.02)

- Accomplishments on the Hack for LA website are:
   - readable even if you don't know anything about the project
   - short
   - clearly articulated achievements that funders would care about
   -  list partners if available

#### Create an issue on your repo to gather/draft project accomplishments
- Add the epic issue to the following project boards:
   - [ ] your project
   - [ ] HfLA: Project Team Tasks
- Search the project's repo for any accomplishment issues, add any links you find to a comment
  - [ ] Go to the project repo issue tab (resource 2.01) and look for any issues previously created for writing accomplishments for the Hack for LA website. It might have the label feature: accomplishments or be named ...Accomplishment Summary for HfLA Website...
-  If there is an issue, compare it to the Accomplishment Issue Template (resource 1.03.01), and update it, so that it has the same steps and resources.
-  If there is no issue called `...Accomplishment Summary for HfLA Website 2020-2024` (or an issue you already made that does the same thing), create the issue now
   - [ ] open a new blank issue on your repository
   - [ ] copy in the title and body from resource 1.03.01
   - [ ] add it to your project board
   - Customize the resources
      - [ ] resource 1.01 with the link to the epic
      - Customize resource 1.04.01 with the link to your one sheet
        - [ ] go to resource 1.05.01 on this epic,
        - [ ] find the file name that corresponds to your project (if there is one there)
        - [ ] add link to resource 1.04.01 on the issue you created.
      - [ ] Customize resource 1.03 with Google Drive for your project and add project name
      - Customize resource 1.04.02 with the Overview link from your project page on hackforla.org
        - [ ] go to [hackforla.org/projects](https://www.hackforla.org/projects)
        - [ ] find your project card
        - If there is an Overview link for your project
           - [ ] add it to 1.04.02
        - If there isn't an Overview link for your project
           - [ ] write `none` after 1.04.02 One sheet link from Hack for LA website (Overview):
      - [ ] Customize 1.04.03 with Project Name
      - Customize 1.05 by adding issue tab link
         - [ ] Copy resource 2.01 in this epic to 1.05 in the new issue
   -  Add the appropriate labels by replacing missing series labels with
      - [ ] size: (Number of years since your repository was created)
      - [ ] role: product or if you have a marketing person marketing role: marketing
      - [ ] p-feature: accomplishments
      - [ ] complexity: large
      - [ ] time sensitive
   -  Add the appropriate milestone
      - [ ] org requirements (if you have this)
      - [ ] project management (if you don't have org requirements)
- Link the issue to this epic
   - [ ] add the issue number to resource 2.02.01
- put the issue you just created in the prioritized backlog
- Put the issue you just created in the prioritized backlog
   - [ ] Place in the prioritized backlog.  Issues with time sensitive labels jump the queue, and are prioritized with other time sensitive issues
- Let the Admin team know that you are finished creating this epic and the child issue
   - [ ] Add a `ready for prioritization` label to this issue

#### work on the issue
- [ ] once the issue has drafts or questions for PM CoP then do the rest of the steps
- Prepare the epic for discussion with Product Management CoP
   - [ ] add a label `ready for product management lead`
   - [ ] move to the questions / review column
   - [ ] add to cop product management agenda for discussion (resource 1.04.01)
- Discussion with Product Management CoP
   - [ ] review the findings and accomplishment drafts in the `...Accomplishment Summary for Website 2020-2024` issue to provide feedback for revision or sign-off
   - [ ] Org rep sign-off
- [ ] Unassign everyone from the issue, add dependency label, and move issue to icebox with the following text
```
October [YYYY] or sooner if there are accomplishments to share
```

### Action items for subsequent years (2025 onward)
- [ ] copy the following into a comment on this epic 
<details><summary>copy block</summary>

```
### Action items for subsequent 2025 onward
#### Create an issue on your repo to gather/draft project 
-  create Accomplishment Summary issue for this year
   - [ ] open a new blank issue on your repository
   - [ ] copy in the title and body from resource 1.03.02
   - [ ] add it to your project board
   - Customize the resources
      - [ ] resource 1.01 with the link to the epic
      - Customize resource 1.04.01 with the link to your one sheet
        - [ ] go to resource 1.05.01 on this epic,
        - [ ] find the file name that corresponds to your project (if there is one there)
        - [ ] add link to resource 1.04.01 on the issue you created.
      - Customize resource 1.04.02 with the Overview link from your project page on hackforla.org
        - [ ] go to [hackforla.org/projects](https://www.hackforla.org/projects)
        - [ ] find your project card
        - If there is an Overview link for your project
           - [ ] add it to 1.04.02
        - If there isn't an Overview link for your project
           - [ ] write `none`
      - [ ] Customize 1.04.03 with Project Name
      - Customize 1.05 by adding issue tab link
         - [ ] Copy resource 2.01 in this epic to 1.05 in the new issue
- [ ] Click on the Submit new issue button
   -  add the appropriate labels
      - [ ] size: 1pt
      - [ ] role: product or if you have a marketing person marketing role: marketing
      - [ ] p-feature: accomplishments
      - [ ] complexity: medium
      - [ ] time sensitive
   -  add the appropriate milestone
      - [ ] org requirements (if you have this)
      - [ ] project management (if you don't have org requirements)
- link the issue to this epic
   - [ ] add the issue number to resource 2.02.02 (or the next number in this series as every year gets added)
- put the issue you just created in the prioritized backlog
- Put the issue you just created in the prioritized backlog
   - [ ] Place in the prioritized backlog.  Issues with time sensitive labels jump the queue, and are prioritized with other time sensitive issues
- Let the Admin team know that you are finished creating this epic and the child issue
   - [ ] Add a `ready for prioritization` label to this issue


#### work on the issue
- [ ] once the issue has drafts or questions for PM CoP then do the rest of the steps
- Prepare the epic for discussion with Product Management CoP
   - [ ] add a label `ready for product management lead`
   - [ ] move to the questions / review column
   - [ ] add to cop product management agenda for discussion (resource 1.04.02)
- Discussion with Product Management CoP
   - [ ] review the findings and accomplishment drafts in the `...Accomplishment Summary for Website [YYYY]` issue to provide feedback for revision or sign-off
   - [ ] Org rep sign-off
```
</details> 

#### Links provided by this issue
- 1.01 This issue is a subset of: Create project and CoP Accomplishment Epics #3
- 1.02 Hackforla.org website, about page, accomplishments section: https://www.hackforla.org/about/#accomplishments
- 1.03 Issue Templates: 
   - 1.03.01 [Project Accomplishment Summary for HfLA Website 2020-2024](https://github.com/hackforla/admin-accomplishments/wiki/issue-template-project-accomplishment-summary-2020-2024)
   - 1.03.02 [Project Accomplishment Summary for HfLA Website [YYYY]](https://github.com/hackforla/admin-accomplishments/wiki/issue-template-project-accomplishment-summary-yyyy)
- 1.04 Product Management CoP Agendas
   - 1.04.01 2024: https://github.com/hackforla/product-management/issues/379
   - 1.04.02 [YYYY] see the pinned issue in the repo https://github.com/hackforla/product-management/issues/
- 1.05 One Sheets for projects
   - 1.05.01 Approved One Sheet Directory of PDFs: https://github.com/hackforla/product-management/tree/master/project-one-sheets
   - 1.05.02 Guide: [How to Write a One Sheet](https://docs.google.com/document/d/14-nYNCjrMrC8lucUNBfLOFQZk2sWbkRlJgigWDAlqlI/edit) - which includes how to update the one sheets, where they are located, etc.

#### Links created by working on this issue
- 2.01 [Civic Tech Index repo, Issues tab](https://github.com/civictechindex/CTI-website-frontend/issues)
- 2.02 Accomplishment Summary issues
   - 2.02.01 2020-2024:
   - 2.02.02 2025:
